#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the beautifulDays function below.
def beautifulDays(i, j, k):
    Reverse = 0
    cn = 0
    for z in range(i,j+1):
        Number = z    
        while(Number > 0):    
            Reminder = Number %10    
            Reverse = (Reverse *10) + Reminder    
            Number = Number //10
        if abs(z-Reverse)%k == 0:
            cn += 1   
        Reverse = 0
    return cn            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ijk = input().split()

    i = int(ijk[0])

    j = int(ijk[1])

    k = int(ijk[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
