#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    # Write your code here
    max1 = max(a)
    max2 = max(b)
    if max1 > max2:
        maxx = max1
    else:
        maxx = max2
    p = 0   
    p1 = 0
    p2 = 0 
    for k in range(1,maxx+1):
        for i in range(n):
            if a[i]!=0 and k%a[i] == 0:
                p1 = p1 + 1

        for j in range(m):
            if b[j]!=0 and b[j]%k == 0:
                p2 = p2 + 1
        
        if p1==n and p2==m:
            p = p + 1        
        p1 = 0
        p2 = 0
    return p        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
