#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    total = 0

    for i in range(n):
        if i!=k:
            total = total + bill[i]
    
    if total/2==b:
        print('Bon Appetit')
    else:    
        print(b-int(total/2))   

if __name__ == '__main__':
    nk = input().rstrip().split()

    n = int(nk[0])

    k = int(nk[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
