#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    low  = scores[0]
    high = scores[0]
    l = 0
    h = 0
    for i in range(1,n):
        if low>scores[i]:
            low = scores[i]
            l = l + 1
        elif  high<scores[i]:
            high = scores[i]
            h = h + 1
    return h,l        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
