#!/bin/python3

import math
import os
import random
import re
import sys
import string

# Complete the designerPdfViewer function below.
def designerPdfViewer(h, word):
    k = 0
    p = [None]*len(word)
    d = dict(zip(string.ascii_lowercase, range(1,27)))    
    for i in range(len(word)):
        p[i] = h[d[word[i]]-1]  #picking letters from word and finding their value from dictionary and then getting their value from h by subtracting 1 from index of h 
        
    k = max(p)
    return(k*len(word))   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
