#!/bin/python3

import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    #
    # Write your code here.
    #from front
    a1 = 0
    b1 = 0
    if p%2==0:
        a1 = p/2
    else:
        a1 = (p-1)/2
    #from back
    if n==p:
        b1 = 0    
    if n%2==0 and p%2==0:
        b1 = (n-p)/2
    if n%2!=0 and p%2==0:
        b1 = int((n-p)/2)
    if n%2!=0 and p%2!=0:
        b1 = (n-p)/2
    if n%2==0 and p%2!=0:
        b1 = int((n-p)/2)+1

    return(min(int(a1),int(b1)))    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
