#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c, k):
    e = 100
    i = 0
    while(1):
        i = (i+k)%n
    #print('i',i)
        if i>=n or i==0:
            i=0
            if c[0]==1:
                e -= 3
            else:
                 e -= 1
            break
       
        e -= 1
        if c[i] == 1:
            e -= 2
            
    return e            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c, k)

    fptr.write(str(result) + '\n')

    fptr.close()
