#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    sp = 0
    sn = 0 
    ze = 0
    for i in range(n):
        if arr[i] > 0:
            sp = sp + 1
        elif arr[i] < 0:
            sn = sn + 1
        else:
            ze = ze + 1
    sp = sp/n
    sn = sn/n
    ze = ze/n 
    print(sp)
    print(sn)
    print(ze)              

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
