#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
def utopianTree(n):
    
    h = 1
    c = 0
    v = 0
    
    for k in range(1,n+1):
            if k%2==0:
                h = h+1
            else:
                h = h*2
    v = h            
    h = 1
    c += 1
    return v


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())
  
    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
